application: oncourseco
version: 0-0-2
runtime: go
api_version: go1
automatic_scaling:
  min_pending_latency: 100ms

handlers:
- url: /
  script: _go_app

- url: /data
  script: _go_app

- url: /SetOAuthCredentials
  script: _go_app
  login: admin

- url: /*
  application_readable: true
  static_dir: www
